# ===============================
# Configurações do Banco de Dados H2
# ===============================
spring.datasource.url=jdbc:h2:mem:lyricsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# Configurações do JPA / Hibernate
# ===============================
# Mostra os comandos SQL no console (ótimo para estudos)
spring.jpa.show-sql=true
# Cria e atualiza as tabelas automaticamente baseado nas nossas Entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ===============================
# Configuração do Swagger (OpenAPI)
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html